import { Link } from 'react-router-dom';import { ArrowRight,Check,Quote } from 'lucide-react';import { insights } from '../data/insights';import { consulting } from '../data/consulting';import { course } from '../data/courses';import { book } from '../data/books';import { profile } from '../data/profile';import { InsightCard,SectionHead } from '../components/Shared';import { SEO } from '../components/SEO';
const services=[['01','외식업 인사이트','외식업 현장에서 필요한 실질적인 정보와 분석을 만나보세요.','/insights'],['02','외식업 컨설팅','매장의 문제를 함께 진단하고 실행 가능한 개선 방향을 찾습니다.','/consulting'],['03','온라인 강의','현장에서 바로 적용할 수 있는 외식업 실무 지식을 배워보세요.','/courses'],['04','종이책','외식업 경험과 노하우를 한 권의 책으로 만나보세요.','/books']];
export default function Home(){return <><SEO title="외식업의 답을 현장과 데이터에서"/><section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">RESTAURANT BUSINESS STUDIO</span><h1>외식업의 답을<br/><em>현장과 데이터</em>에서<br/>찾습니다.</h1><p>외식업 현장에서 얻은 경험과 데이터를 바탕으로<br/>매장의 문제를 함께 분석하고 실행 가능한 해답을 찾습니다.</p><div className="actions"><Link className="btn" to="/insights">인사이트 보기 <ArrowRight size={17}/></Link><Link className="btn secondary" to="/consulting">컨설팅 알아보기</Link></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1516211697506-8360dbcfe9a4?auto=format&fit=crop&w=1600&q=85" alt="따뜻한 조명의 레스토랑에서 일하는 셰프"/><div className="image-note"><b>현장 중심의 관찰</b><span>매장의 하루에서 변화의 실마리를 찾습니다.</span></div></div></div></section>
<section className="service-strip"><div className="container services">{services.map(s=><Link to={s[3]} key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><ArrowRight/></Link>)}</div></section>
<section><div className="container"><SectionHead eyebrow="LATEST INSIGHTS" title={'지금, 현장에서 필요한 이야기'} desc="유행보다 오래 남는 원칙과 당장 적용할 수 있는 방법을 나눕니다." action="전체 인사이트"/><div className="insight-grid">{insights.slice(0,6).map(i=><InsightCard item={i} key={i.slug}/>)}</div></div></section>
<section className="consulting-feature"><div className="container consulting-grid"><div><span className="eyebrow light-label">CONSULTING</span><h2>혼자 고민하지 마세요.<br/>매장의 문제를 함께 들여다봅니다.</h2><p>정답을 대신 말하기보다, 매장의 상황과 숫자를 함께 읽고 지속 가능한 실행 방법을 찾습니다.</p><div className="actions"><Link className="btn cream" to="/consulting">컨설팅 자세히 보기</Link><Link className="btn line-light" to="/contact">상담 문의하기</Link></div></div><div className="consult-types"><div><span>01 · OFFLINE</span><h3>오프라인 컨설팅</h3><ul>{consulting.offline.map(x=><li key={x}><Check/> {x}</li>)}</ul></div><div><span>02 · ONLINE</span><h3>온라인 컨설팅</h3><ul>{consulting.online.map(x=><li key={x}><Check/> {x}</li>)}</ul></div></div></div></section>
<section><div className="container feature-grid"><div className="feature-image"><img src={course.image} alt="테이블에서 외식업 실무 강의를 논의하는 모습" loading="lazy"/><span>ONLINE CLASS · 01</span></div><div className="feature-copy"><span className="eyebrow">ONLINE CLASS</span><h2>{course.title}</h2><p className="lead">{course.description}</p><dl><div><dt>추천 대상</dt><dd>{course.audience}</dd></div><div><dt>강의 시간</dt><dd>{course.duration}</dd></div><div><dt>수강 방식</dt><dd>온라인 · 기간 내 자유 수강</dd></div></dl><div className="tag-row">{course.features.map(x=><span key={x}>{x}</span>)}</div><div className="actions"><Link className="btn" to="/courses">강의 자세히 보기</Link><Link className="text-link" to="/contact">수강 문의 <ArrowRight size={17}/></Link></div></div></div></section>
<section className="book-section"><div className="container book-grid"><div className="book-cover"><small>RESTAURANT<br/>BUSINESS<br/>ESSENTIALS</small><h3>장사는<br/>감이 아니라<br/><em>구조입니다</em></h3><p>김현장 지음</p></div><div><span className="eyebrow">PAPER BOOK</span><h2>현장에서 얻은 경험을<br/>한 권의 책에 담았습니다.</h2><h3>{book.title}</h3><p>{book.description}</p><ul className="check-list">{book.recommend.map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="actions"><Link className="btn" to="/books">책 자세히 보기</Link><Link className="text-link" to="/contact">구매 문의 <ArrowRight size={17}/></Link></div></div></div></section>
<section><div className="container profile-grid"><div className="profile-image"><img src={profile.image} alt="외식업 컨설턴트 프로필 예시" loading="lazy"/><Quote/></div><div><span className="eyebrow">ABOUT US</span><h2>현장을 이해해야<br/>좋은 답을 찾을 수 있습니다.</h2><p className="lead">{profile.bio}</p><b>{profile.name}</b><span className="role">{profile.role} · {profile.career}</span><div className="actions"><Link className="text-link" to="/about">소개 더 보기 <ArrowRight size={17}/></Link></div></div></div></section><BottomCTA/></>}
export function BottomCTA(){return <section className="bottom-cta"><div className="container"><span>LET'S TALK</span><h2>지금 매장에서<br/>가장 고민되는 것은 무엇인가요?</h2><p>매장의 상황을 알려주시면 함께 문제를 살펴보겠습니다.</p><Link className="btn cream" to="/contact">컨설팅 문의하기 <ArrowRight size={17}/></Link></div></section>}
